export const FOLLOWING_USERS_POST_REQUEST = "FOLLOWING_USERS_POST_REQUEST"
export const FOLLOWING_USERS_POST_SUCCESS = "FOLLOWING_USERS_POST_SUCCESS"
export const FOLLOWING_USERS_POST_FAILURE = "FOLLOWING_USERS_POST_FAILURE"


export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST"
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE"


export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE"


export const MY_POST_REQUEST = "MY_POST_REQUEST"
export const MY_POST_SUCCESS = "MY_POST_SUCCESS"
export const MY_POST_FAILURE = "MY_POST_FAILURE"


export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE"


export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE"