export const FOLLOWING_USERS_POST_REQUEST = "FOLLOWING_USERS_POST_REQUEST"
export const FOLLOWING_USERS_POST_SUCCESS = "FOLLOWING_USERS_POST_SUCCESS"
export const FOLLOWING_USERS_POST_FAILURE = "FOLLOWING_USERS_POST_FAILURE"
