export const FOLLOWING_USERS_POST_REQUEST = "FOLLOWING_USERS_POST_REQUEST"
export const FOLLOWING_USERS_POST_SUCCESS = "FOLLOWING_USERS_POST_SUCCESS"
export const FOLLOWING_USERS_POST_FAILURE = "FOLLOWING_USERS_POST_FAILURE"


export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST"
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE"


export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE"